### PR TITLE
Hotfix/enable receiving large http(s) requests in nginx config

### PR DESCRIPTION
**Pull request by SamSirry**
Reference issue: https://github.com/turnkeylinux/tracker/issues/1747

### CODE REVIEW

**Comment by SamSirry** [comment]
I'm still novice with git. It seems two fixes came together in this pull request. Sorry.

**Comment by JedMeister** [comment]
Thanks for your contribution @SamSirry!

I'm generally ok with appliance build code PRs that resolve multiple issues, although I do prefer that multiple issues are done addressed in separate commits. So on face value, you're all good! :smile: 

In essence, I'm ok with the changes your making. Adding IPv6 support is a great idea, thanks for that! Also applying the fix that closes a bug is another great job. Although I do have a couple of thoughts.

Firstly, your second commit undoes the first?! I.e. you added IPv6 support, then removed it again when you added the `client_max_body_size`?! See here: https://github.com/turnkeylinux-apps/gitea/pull/5/commits/5234ee8428ed86c34e8c77e651eced2b0207317e

And adding the `client_max_body_size` might actually be cleaner in the `/etc/nginx/include/gitea-proxy` file? I.e. instead adding the line twice to `/etc/nginx/sites-available/gitea` (one for each `server {}` block), just add it once to (the `location {}` block in) `/etc/nginx/include/gitea-proxy`:
```
diff --git a/overlay/etc/nginx/include/gitea-proxy b/overlay/etc/nginx/include/gitea-proxy
index 5be3236..8ba4e76 100644
--- a/overlay/etc/nginx/include/gitea-proxy
+++ b/overlay/etc/nginx/include/gitea-proxy
@@ -9,6 +9,7 @@ location / {
 }
 
 location @gitea {
+    client_max_body_size 0;
     proxy_set_header Host $host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
What do you think? According to [Ngixnx docs](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) it's valid within a `location {}` block. Would you mind testing to double check that it works as intended?

Assuming you are using git from the CLI, here's how to undo your most recent commit, reset to the commit that added IPv6:
```
git reset --hard 5abe89c
```
Then if you confirm my suggestion works and are happy to add that too, then make the change. Before you commit, do a `git diff` to ensure that it includes the changes you want. Then add the file and create a new commit and push.
```
git diff path/to/file
git add path/to/file
git commit -m "commit message..."
git push REMOTE BRANCH
```
(Where `path/to/file` is the actual path, `REMOTE` is the remote name, e.g. `origin` & `BRANCH` is the actual branch name).

**Comment by SamSirry** [comment]
What happened is that I committed the first update to the main branch, then I remembered that I should have branched a hotfix, but I didn't know how to roll back..

So I tried what seemed like creating a branch, under which I added the other update, then tried to merge and it became a mess.

Eventually I decided I MUST learn to git properly, and so I'm having a crash course right now. (and I realize now why the mess happened).

I should be able to test your suggestions after the weekend, and hopefully by then I will not be messing up the main branch 😄 

Thank you for your kind assistance and helpful details 👍 🙇

**Comment by JedMeister** [comment]
No problems. We all start out being crap at stuff we don't know! :smile: 

Chat more soon and don't be scared to ask if you get stuck.

**Comment by SamSirry** [comment]
Thank you for your patience, @JedMeister.
I'm using SourceTree as a git GUI.  Not afraid of CLI, but I find it more practical, and visually pleasing.

I've just submitted a PR with the intended fixes merged into `master`. I hope I've done it properly this time :)
Please let me know if I should have submitted two PRs, one for each fix. And in this case, should I do the PR for the fix-branch, or for the `master` branch after merging each fix one-by-one?

p.s.: the fixes are tested and working.

**Comment by JedMeister** [comment]
No worries @SamSirry Apologies for my slow response. I'll close this one and merge the other.

**Pull request closed without merging**
